// <auto-generated />
using System;
using DROrdenes.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DROrdenes.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("DROrdenes.Entidades.Ordenes", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.HasKey("OrdenId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("DROrdenes.Entidades.OrdenesDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cantidad")
                        .HasColumnType("REAL");

                    b.Property<double>("Costo")
                        .HasColumnType("REAL");

                    b.Property<int>("OrdenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.HasIndex("ProductoId");

                    b.ToTable("OrdenesDetalle");
                });

            modelBuilder.Entity("DROrdenes.Entidades.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<double>("Inventario")
                        .HasColumnType("REAL");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Costo = 70m,
                            Descripcion = "Pan",
                            Inventario = 150.0
                        },
                        new
                        {
                            ProductoId = 2,
                            Costo = 20m,
                            Descripcion = "Jugos Ya",
                            Inventario = 230.0
                        },
                        new
                        {
                            ProductoId = 3,
                            Costo = 50m,
                            Descripcion = "Coca Cola",
                            Inventario = 110.0
                        },
                        new
                        {
                            ProductoId = 4,
                            Costo = 42m,
                            Descripcion = "Chocolate Cortes",
                            Inventario = 197.0
                        },
                        new
                        {
                            ProductoId = 5,
                            Costo = 317m,
                            Descripcion = "Arroz Campo",
                            Inventario = 215.0
                        });
                });

            modelBuilder.Entity("DROrdenes.Entidades.Suplidores", b =>
                {
                    b.Property<int>("SuplidorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.HasKey("SuplidorId");

                    b.ToTable("Suplidores");

                    b.HasData(
                        new
                        {
                            SuplidorId = 1,
                            Nombres = "PapiGreza"
                        },
                        new
                        {
                            SuplidorId = 2,
                            Nombres = "Nesttle"
                        },
                        new
                        {
                            SuplidorId = 3,
                            Nombres = "La Sirena"
                        },
                        new
                        {
                            SuplidorId = 4,
                            Nombres = "Porvenir"
                        },
                        new
                        {
                            SuplidorId = 5,
                            Nombres = "Palmares"
                        });
                });

            modelBuilder.Entity("DROrdenes.Entidades.OrdenesDetalle", b =>
                {
                    b.HasOne("DROrdenes.Entidades.Ordenes", null)
                        .WithMany("Detalle")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DROrdenes.Entidades.Productos", "productos")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
